const express = require("express");
const router = express.Router();

const dashboardRoutes = require("../routes/dashboard");
const queryRoutes = require("../routes/query.routes.js");
const influencerJobRequestRoutes = require("../routes/influencerJobRequest.routes.js");
const subscriptionRouter = require("../routes/subscription.routes.js");
const sessionRoute = require("../routes/session.js");
const addaRouter = require("../routes/adda.routes.js");
const userRoutes = require("../routes/user.js");
const emailRoutes = require("../routes/email");
const productRoutes = require("../routes/product.routes.js");
const otpRoutes = require("../routes/otp");
const workshopRoutes = require("../routes/workshop");
const whatsappRoutes = require("../routes/whatsapp.js");
const adminRoutes = require("../routes/admin.js");
const uploadRoutes = require("../routes/upload.js");
const careerRoutes = require("../routes/career");
const userContributedPodcastRoutes = require("../routes/userContributionRoute.js");
const callRequestRoutes = require("../routes/callRequests.js");
const authorRoutes = require("../routes/author.js");
const reviewRoutes = require("../routes/review");
const skuRoutes = require("../routes/cardProductRoutes.js");
const upload = require("../middlewares/uploadFileMiddleware.js");
const cartRoutes = require("../routes/cartRoutes.js");
const paymentRoutes = require("../routes/paymentRoutes.js");
const mythosCommentRoutes = require("../routes/mythosComment.routes.js");
const commentRoutes = require("../routes/comment.routes.js");
const postRoutes = require("../routes/post.routes.js");
const likeRoutes = require("../routes/like.routes.js");
const shareRoutes = require("../routes/share.routes.js");
const feedRoutes = require("../routes/feed.routes.js");
const memeRoutes = require("../routes/adda/meme.routes.js");
const memeFeedRoutes = require("../routes/adda/memeFeed.routes.js");
const rewardRoutes = require("../routes/rewardRoutes.js");
const adminRewardRoutes = require("../routes/adminRewardRoutes.js");
const reactionRoutes = require("../routes/reactionRoutes");
const sessionCallRoutes = require("../routes/admin/sessionCall.js");
const orderRouter = require("../routes/orders.routes.js");
const conversationRouter = require("../routes/adda/conversation.routes.js");
const groupRoutes = require("../routes/adda/group.routes.js");
const attendanceRoutes = require("../routes/employee/attendance.routes.js");
const leaveRoutes = require("../routes/employee/leave.routes.js");
const gameRoutes = require("../routes/adda/game.routes.js");
const dataCaptureRoutes = require("../routes/employee/dataCapture.routes.js");
const evaluationRoutes = require("../routes/EvaluationForm.js");
const employeeRouter = require("../routes/employee/empoyee.routes");
const meetupRoutes = require("../routes/adda/meetup.routes.js");
const quizRoutes = require("../routes/adda/quiz.routes.js");
const contestRoutes = require("../routes/adda/contest.routes.js");
const ensureUserExists = require("../middlewares/ensureUserExists");
const clerkWebhook = require("../controllers/webhook/clerkWebhook.controller.js");

router.post("/webhook/clerk", ensureUserExists, clerkWebhook);

router.use("/adda", addaRouter);
router.use("/influencer-requests", influencerJobRequestRoutes);
router.use("/email", emailRoutes);
router.use("/whatsapp", whatsappRoutes);
router.use("/products", productRoutes);
router.use("/otp", otpRoutes);
// app.use("/quiz", quizRoutes);
router.use("/workshop", workshopRoutes);
router.use("/user", userRoutes);
router.use("/admin", adminRoutes);
router.use("/upload", upload.single("file"), uploadRoutes);
router.use("/career", careerRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/userContribution", userContributedPodcastRoutes);
router.use("/call-requests", callRequestRoutes);
router.use("/author", authorRoutes);
router.use("/evaluation", evaluationRoutes);
router.use("/review", reviewRoutes);
router.use("/sku", skuRoutes);
router.use("/cart", cartRoutes);
router.use("/payment", paymentRoutes);
router.use("/sessionbookings", sessionRoute);
router.use("/query", queryRoutes);
router.use("/mythosComment", mythosCommentRoutes);
router.use("/comments", commentRoutes);
router.use("/posts", postRoutes);
router.use("/likes", likeRoutes);
router.use("/shares", shareRoutes);
router.use("/feeds", feedRoutes);
router.use("/memes", memeRoutes);
router.use("/memeFeed", memeFeedRoutes);
router.use("/rewards", rewardRoutes);
router.use("/admin/rewards", adminRewardRoutes);
router.use("/reactions", reactionRoutes);
router.use("/order", orderRouter);
router.use("/subscription", subscriptionRouter);
router.use("/conversation", conversationRouter);
router.use("/employee", employeeRouter);
router.use("/sessions", sessionCallRoutes);
router.use("/meetup", meetupRoutes);
router.use("/groups", groupRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/leave", leaveRoutes);
router.use("/quiz", quizRoutes);
router.use("/contest", contestRoutes);
router.use("/game", gameRoutes);
router.use("/data-capture", dataCaptureRoutes);

module.exports = router;
