module.exports = {
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    BAD_REQUEST: 'Bad Request',
    NEWSLETTER_SUBSCRIBED: 'Subscribed to newsletter succesfully',
    FREE_DOWNLOAD_CLAIMED: 'You have successfully claimed your free gift',
    PRODUCT_CREATED:'Product created succesfully',
    PRODUCTS_FETCHED:'Products  fetchhed successfully',
    PRODUCT_UPDATED:'Product updated successfully',
    PRODUCT_DELETED:'Product deleted successfully',
    PRODUCT_NOT_FOUND:'Product not found',
    OTP_SENT_SUCCESSFULLY:'OTP sent successfully',
    OTP_VERIFIED:"OTP verified successfully",
    INVALID_OTP:"Invalid OTP",
    OTP_NOT_FOUND:"OTP not found",
    QUESTION_LIMIT:"A quiz must have between 2 and 5 questions.",
    ANSWER_LIMIT:"A answer must have 5 additional details",
    QUIZ_CREATED:'Quiz created sucessfully',
    FORM_SUBMITTED:"Form submitted successfully",
} 