module.exports = {
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  BAD_REQUEST: "Bad Request",
  NEWSLETTER_SUBSCRIBED: "Subscribed to newsletter succesfully",
  FREE_DOWNLOAD_CLAIMED: "You have successfully claimed your free gift",
  PRODUCT_CREATED: "Product created succesfully",
  PRODUCTS_FETCHED: "Products  fetchhed successfully",
  PRODUCT_UPDATED: "Product updated successfully",
  PRODUCT_DELETED: "Product deleted successfully",
  PRODUCT_NOT_FOUND: "Product not found",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
  OTP_VERIFIED: "OTP verified successfully",
  INVALID_OTP: "Invalid OTP",
  OTP_NOT_FOUND: "OTP not found",
  SUCCESSFULLY_CREATED_USER: "Successfully created user.",
  EMAIL_ALREADY_EXIST: "Email already Exist",
  USER_UNAUTHORIZE: "User with this email does not exist",
  INCORRECT_PASSWORD: "Incorrect Password",
  SUCCESSFULLY_REGISTERED_USER: "Successfully Register user",
  SUCCESSFULLY_LOGGED_IN_USER: "Successfully Logged in user.",
  SUCCESSFULLY_LOGOUT_USER: "Successfully logged out.",
  QUESTION_LIMIT: "A quiz must have between 2 and 5 questions.",
  ANSWER_LIMIT: "A answer must have 5 additional details",
  QUIZ_CREATED: "Quiz created sucessfully",
  FORM_SUBMITTED: "Form submitted successfully",
  FILE_UPLOAD_SUCCESS: "File uploaded successfully",
  FILE_UPLOAD_FAILED: "File upload failed",
  NO_FILE_UPLOADED: "No file uploaded",
  FILE_NOT_FOUND: "File not found",
  FILE_BUFFER_MISSING: "File buffer is missing",
  FILE_DELETED_SUCCESSFULLY: "File deleted successfully",
  FILE_DELETION_FAILED: "File deletion failed",
  JOB_CREATED: "Job created successfully",
  JOB_FETCHED: "Job fetched successfully",
  JOB_NOT_FOUND: "Job not found",
  JOB_UPDATED: "Job updated successfully",
  JOB_DELETED: "Job deleted successfully",
  JOB_APPLICATION_CREATED: "Job application created successfully",
  JOB_APPLICATION_FETCHED: "Job application fetched successfully",
  JOB_APPLICATION_NOT_FOUND: "Job application not found",
  JOB_APPLICATION_UPDATED: "Job application updated successfully",
  USER_FETCHED_SUCCESSFULLY: "User data fetched successfully",
  USER_DOESNT_EXISTS: "User doesn't exists",
  USER_BLACKLIST: "User blacklisted successfully",
  EMAIL_SENT: "Email sent successfully",
};
